POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1haW1laSIsImlkIjoiNWNjNWJjOWVlZDU3MzEyNGZkZTcxMDE5IiwiaWF0IjoxNTU2NDY3NDU2fQ.fKsiKFBUehlpHrv95nRg997M04SPXqMBEcyi6mqxRgk

{
  "title": "Canonical string reduction",
  "author": "Edsger W. Dijkstra",
  "url": "http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html",
  "likes": 12
}